In [6]:
import numpy as np
import pandas as pd

In [7]:
s = pd.Series([1,2,3,4] , index=["a","b","c","d"])
s

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
data ={
    "Uid":[101 , 201 , 401],
    "Name":["Amit" , "Anand" , "Akash"],
    "Age":[25 , 28 , 30],
    "City":["Mumbai" , "Delhi" , "Patna"],
}

df = pd.DataFrame(data)
df

   Uid   Name  Age    City
0  101   Amit   25  Mumbai
1  201  Anand   28   Delhi
2  401  Akash   30   Patna

In [9]:
df.columns

Index(['Uid', 'Name', 'Age', 'City'], dtype='str')

In [10]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [20]:
df[df["Name"].str.endswith("h")]

   Uid   Name  Age   City
2  401  Akash   30  Patna

In [25]:
import numpy as np
matrix_data = np.matrix('22,160,70;42,170,80;30,175,90;35,160,70;25,140,70')

column_heading = ["Age" , "Weight" , "Height"]
idx = ["A","B","C","D","E"]

df = pd.DataFrame(matrix_data , columns=column_heading , index=idx)
df

   Age  Weight  Height
A   22     160      70
B   42     170      80
C   30     175      90
D   35     160      70
E   25     140      70

In [28]:
df[df["Height"]>70]

   Age  Weight  Height
B   42     170      80
C   30     175      90

In [31]:
df.reset_index()

  index  Age  Weight  Height
0     A   22     160      70
1     B   42     170      80
2     C   30     175      90
3     D   35     160      70
4     E   25     140      70

In [32]:
df.reset_index(drop=True)

   Age  Weight  Height
0   22     160      70
1   42     170      80
2   30     175      90
3   35     160      70
4   25     140      70

In [38]:
df["BMI"] = ((df["Weight"])/(df["Height"]/100)**2).round(2)
df

   Age  Weight  Height     BMI
A   22     160      70  326.53
B   42     170      80  265.62
C   30     175      90  216.05
D   35     160      70  326.53
E   25     140      70  285.71

In [42]:
df.columns = df.columns.str.lower()

In [43]:
df

   age  weight  height     bmi
A   22     160      70  326.53
B   42     170      80  265.62
C   30     175      90  216.05
D   35     160      70  326.53
E   25     140      70  285.71