In [87]:
import numpy as np
import pandas as pd

In [88]:
df = pd.DataFrame(
    {
        "A":[1,2,np.nan],
        "B":[5,np.nan,np.nan],
        "C":[1,2,3]
    }
)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [89]:
df["Country"] = "IN US ENG".split()
df

     A    B  C Country
0  1.0  5.0  1      IN
1  2.0  NaN  2      US
2  NaN  NaN  3     ENG

In [90]:
df.set_index("Country" , inplace=True)

In [91]:
df

           A    B  C
Country
IN       1.0  5.0  1
US       2.0  NaN  2
ENG      NaN  NaN  3

In [92]:
df.dropna()

           A    B  C
Country
IN       1.0  5.0  1

In [93]:
df.dropna(axis=1)

         C
Country
IN       1
US       2
ENG      3

In [94]:
mean_A = df["A"].mean()
mean_B = df["B"].mean()
mean_C = df["C"].mean()
df.fillna({"A" : mean_A , "B" : mean_B , "C" : mean_C} , inplace=True)

           A    B  C
Country
IN       1.0  5.0  1
US       2.0  5.0  2
ENG      1.5  5.0  3

In [95]:
data = {
    'Company' : [ 'GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB' ],
    'Person': ['Aman', 'Ankit', 'Aditya', 'Anjali', 'Ankita', 'Ayush'],
    'Sales': [200,120,340, 124, 243, 350]
}
df = pd.DataFrame(data)
df

  Company  Person  Sales
0    GOOG    Aman    200
1    GOOG   Ankit    120
2    MSFT  Aditya    340
3    MSFT  Anjali    124
4      FB  Ankita    243
5      FB   Ayush    350

In [96]:
df.groupby("Company").Sales.mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [97]:
df.groupby("Company").describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [98]:


df1 = pd.DataFrame(
    {
        'A': ['A0', 'A1', 'A2', 'A3'],
        'B': ['B0', 'B1', 'B2', 'B3'],
        'C': ['C0', 'C1', 'C2', 'C3'],
        'D': ['D0', 'D1', 'D2', 'D3'],
    },
    index=[0, 1, 2,3]
)

df2 = pd.DataFrame(
    {
        'A': ['A4', 'A5', 'A6', 'A7'],
        'B': ['B4', 'B5', 'B6', 'B7'],
        'C': ['C4', 'C5', 'C6', 'C7'],
        'D': ['D4', 'D5', 'D6', 'D7'],
    },
    index=[4,5,6,7]
)

df3 = pd.DataFrame(
    {
        'A': ['A8', 'A9', 'A10', 'A11'],
        'B': ['B8', 'B9', 'B10', 'B11'],
        'C': ['C8', 'C9', 'C10', 'C11'],
        'D': ['D8', 'D9', 'D10', 'D11'],
    },
    index=[8,9,10,11]
)

In [99]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [100]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [101]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#### Concatenation along axis 0 , Row-Wise Concatenation

In [102]:
pd.concat([ df1 , df2 , df3 ] , axis=0)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#### Concatenation along axis 1 , Column-Wise

In [103]:
pd.concat([df1 , df2 , df3] , axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [104]:
df1 = pd.DataFrame(
    {
        'A': ['A0', 'A1', 'A2', 'A3'],
        'B': ['B0', 'B1', 'B2', 'B3'],
        'C': ['C0', 'C1', 'C2', 'C3'],
        'D': ['D0', 'D1', 'D2', 'D3'],
    },
    index=[0,1,2,3]
)

df2 = pd.DataFrame(
    {
        'A': ['A4', 'A5', 'A6', 'A7'],
        'B': ['B4', 'B5', 'B6', 'B7'],
        'C': ['C4', 'C5', 'C6', 'C7'],
        'D': ['D4', 'D5', 'D6', 'D7'],
    },
    index=[0,1,2,3]
)

df3 = pd.DataFrame(
    {
        'A': ['A8', 'A9', 'A10', 'A11'],
        'B': ['B8', 'B9', 'B10', 'B11'],
        'C': ['C8', 'C9', 'C10', 'C11'],
        'D': ['D8', 'D9', 'D10', 'D11'],
    },
    index=[0,1,2,3]
)

In [105]:
pd.concat([df1 , df2 , df3] , axis=1)

    A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [106]:
pd.concat([ df1 , df2 , df3 ] , axis=0)

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [107]:
left = pd.DataFrame({
    'key': ['K0', 'K1', 'K9', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

right = pd.DataFrame({
    'key': ['K0', 'K8', 'K2', 'K3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})

In [108]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K9  A2  B2
3  K3  A3  B3

In [109]:
right

  key   C   D
0  K0  C0  D0
1  K8  C1  D1
2  K2  C2  D2
3  K3  C3  D3

#### Merge

```python
pd.merge(
    left , right,
    on=None,
    how='inner',
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    suffixes=('_x','_y')
)

In [110]:
merge1 = pd.merge(
    left,right,
    on='key',
)
merge1

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K3  A3  B3  C3  D3

In [111]:
# create DF

left = pd.DataFrame({
    'key1':['K0', 'K0', 'K1', 'K2'],
    'key2': ['K0', 'K1', 'K0', 'K1'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B':['B0', 'B1', 'B2', 'B3']
})

right = pd.DataFrame({
    'key1':['K0', 'K1','K1','K2'],
    'key2': ['K0', 'K0', 'K0', 'K0'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})

print("\nThe DataFrame 'left'\n",'-'*30, sep='')
print(left)

print("\nThe DataFrame 'right'\n",'-'*30, sep='')
print(right)

The DataFrame 'left'
------------------------------
  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

The DataFrame 'right'
------------------------------
  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [112]:
merge2 = pd.merge(
    left , right,
    on=["key1","key2"]
)
merge2

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

#### Left Merge

In [113]:
left_merge = pd.merge(
    left , right,
    on=["key1" , "key2"],
    how="left"
)
left_merge

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

#### Right Merge

In [114]:
right_merge = pd.merge(
    left , right,
    on=["key1","key2"],
    how="right"
)
right_merge

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [115]:
outer_merge = pd.merge(
    left , right,
    on=["key1" , "key2"],
    how="outer"
)
outer_merge

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [117]:
left = pd. DataFrame(
    {
        'A': ['A0', 'A1', 'A2'],
        'B': ['BO', 'B1', 'B2']
    },
    index=['K0', 'K1', 'K2']
)

right = pd.DataFrame(
    {
        'C': ['co', 'C2', 'C3'],
        'D': ['DO', 'D2', 'D3']
    },
    index=['K0', 'K2', 'K3'])

print("\nThe DataFrame 'left'\n", '-'*30, sep='')
print(left)

print("\nThe DataFrame 'right'\n",'-'*30, sep='')
print(right)

The DataFrame 'left'
------------------------------
     A   B
K0  A0  BO
K1  A1  B1
K2  A2  B2

The DataFrame 'right'
------------------------------
     C   D
K0  co  DO
K2  C2  D2
K3  C3  D3

#### Left Join (Similar as Left Outer Join)

In [118]:
left.join(right)

     A   B    C    D
K0  A0  BO   co   DO
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

#### Right Join (Similar to Right Outer Join)

In [119]:
right.join(left)

     C   D    A    B
K0  co  DO   A0   BO
K2  C2  D2   A2   B2
K3  C3  D3  NaN  NaN