### For multi-Dimensional Data we use Multi-indexing , we use multiple of column's index as once

In [27]:
import numpy as np
import pandas as pd

In [28]:
arrays = [
    ['North' , 'North' , 'South' , 'South' , "East"],
    [2024 , 2025 , 2024 , 2025 , 2026]
]

In [29]:
index = pd.MultiIndex.from_arrays(arrays , names=("Region","Year"))

In [30]:
index

MultiIndex([('North', 2024),
            ('North', 2025),
            ('South', 2024),
            ('South', 2025),
            ( 'East', 2026)],
           names=['Region', 'Year'])

In [ ]:
df = pd.DataFrame(
    np.random.randint(100 , 500 , size=(5,2)),
    index=index,
    columns=["Products_A","Products_B"]
)
df

             Products_A  Products_B
Region Year
North  2024         161         363
       2025         338         291
South  2024         134         308
       2025         180         150
East   2026         204         494

:

In [32]:
df.xs('North' , level="Region")

      Products_A  Products_B
Year
2024         395         287
2025         427         200

In [36]:
df.xs(2024 , level="Year")

        Products_A  Products_B
Region
North          395         287
South          377         110