In [1]:
import pandas as pd
from data import Data
obj = Data()
df=obj.data()

In [2]:
df[["Name" , "Sex" , "Cabin"]].head(10)

                                                Name     Sex Cabin
0                            Braund, Mr. Owen Harris    male   NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   C85
2                             Heikkinen, Miss. Laina  female   NaN
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  C123
4                           Allen, Mr. William Henry    male   NaN
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male   E46
7                     Palsson, Master. Gosta Leonard    male   NaN
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   NaN
9                Nasser, Mrs. Nicholas (Adele Achem)  female   NaN

In [3]:
df["Name"].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [4]:
df["Name"] = df["Name"].str.capitalize()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, mr. william henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, mr. karl howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, mr. patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df["Name"] = df["Name"].str.replace("mr" , "sir")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, sir. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, sirs. john bradley (florence briggs t...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, sirs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, sir. william henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df["Name"] = df["Name"].replace({
    r"\bMrs\b": "ma'am",
    r"\bMr\b": "sir"
}, regex=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, sir. owen harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, sirs. john bradley (florence briggs t...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, sirs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, sir. william henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, rev. juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, miss. catherine helen ""carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, sir. karl howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, sir. patrick",male,32.0,0,0,370376,7.7500,NaN,Q