In [3]:
import pandas as pd

In [5]:
data = {
    "name" : ["Sumit" , "Shivam" , "Shivang" , "Shiva"],
    "age" : [21 , 13 , 12 , 15],
    "city" : ["Bengaluru" , "Mumbai" , "Pune" , "Hydrabad"]
}

In [8]:
df = pd.DataFrame(data)
df

      name  age       city
0    Sumit   21  Bengaluru
1   Shivam   13     Mumbai
2  Shivang   12       Pune
3    Shiva   15   Hydrabad

In [11]:
data_2 = [
    {"name":"Sumit" , "age":21 , "city":"Bengaluru"},
    {"name":"Shivam" , "age":13 , "city":"Mumbai"},
    {"name":"Shivang" , "age":12 , "city":"Pune"},
    {"name":"Shiva" , "age":15 , "city":"Hydrabad"}
]

df_2 = pd.DataFrame(data_2)
df_2

      name  age       city
0    Sumit   21  Bengaluru
1   Shivam   13     Mumbai
2  Shivang   12       Pune
3    Shiva   15   Hydrabad

### Accessing the value

In [ ]:
print("Name Column")
print(df['name'] , "\n")

print("City Column")
print(df.age , "\n")

print("2nd index of City Column")
print(df.city[2] , "\n")

Name Column
0      Sumit
1     Shivam
2    Shivang
3      Shiva
Name: name, dtype: str

City Column
0    21
1    13
2    12
3    15
Name: age, dtype: int64

2nd index of City Column
Pune

In [28]:
print(df.loc[0],"\n")
print(df.loc[0:1],"\n")

print(df.iloc[2],"\n")
print(df.iloc[2:4],"\n")

name        Sumit
age            21
city    Bengaluru
Name: 0, dtype: object

     name  age       city
0   Sumit   21  Bengaluru
1  Shivam   13     Mumbai

name    Shivang
age          12
city       Pune
Name: 2, dtype: object

      name  age      city
2  Shivang   12      Pune
3    Shiva   15  Hydrabad