In [55]:
import pandas as pd

In [96]:
titanic_dataset = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# last five rows
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.Name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [ ]:
df[["Name" , "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [ ]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
df.loc[0 , "Name"]

'Braund, Mr. Owen Harris'

In [ ]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
df.iloc[0 , 3] # row 0 and column 3(column 3 contains Name)

'Braund, Mr. Owen Harris'

### Conditional Selection

In [ ]:
# get all the rows where person age > 70

df[df["Age"]>70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [ ]:
# Get all the females who survived
df[ (df["Sex"]=="female")  & (df["Survived"] == 1) ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [94]:
# Get only name and age of all the females who survived 

survived_female = df[ (df["Sex"]=="female") & (df["Survived"]==1) ]
name_age = survived_female[["Name" , "Age"]]
name_age

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [75]:
name_age.head(10)

                                                 Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0
19                            Masselmani, Mrs. Fatima   NaN
22                        McGowan, Miss. Anna "Annie"  15.0

In [93]:
# Total Number Of survivors

survived = len(df[df["Survived"]==1])
not_survived = len(df[df["Survived"]==0])

# Percentage Survived
print(f"{round( ( survived/(survived+not_survived) )*100 , 2 )} % Survived")

#percentage Not Survived
print(f"{round( ( not_survived/(survived+not_survived) )*100 , 2 )} % Not Survived")

38.38 % Survived
61.62 % Not Survived

In [103]:
# use of loc in DataFrame
# df.loc(DataFrame , index)
df.loc[(df["Sex"]=="female") & (df["Survived"]==1) , ["Name" , "Age"]]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [112]:
df.loc[ : 9 , ["Name" , "Cabin"]]

                                                Name Cabin
0                            Braund, Mr. Owen Harris   NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
2                             Heikkinen, Miss. Laina   NaN
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
4                           Allen, Mr. William Henry   NaN
5                                   Moran, Mr. James   NaN
6                            McCarthy, Mr. Timothy J   E46
7                     Palsson, Master. Gosta Leonard   NaN
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   NaN
9                Nasser, Mrs. Nicholas (Adele Achem)   NaN