In [67]:
import pandas as pd
titanic_dataset = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset)
df

URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

### Indexing

In [ ]:
df.loc[4]

PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object

In [ ]:
df.loc[4:9 , ["Name" , "Age"]]

                                                Name   Age
4                           Allen, Mr. William Henry  35.0
5                                   Moran, Mr. James   NaN
6                            McCarthy, Mr. Timothy J  54.0
7                     Palsson, Master. Gosta Leonard   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

### Slicing Rows

In [ ]:
df.loc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Slicing Columns

In [ ]:
df.loc[ : , ["Name" , "Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [ ]:
df.iloc[:,[2,4]] # it'll return column at 2th and 4th index

     Pclass     Sex
0         3    male
1         1  female
2         3  female
3         1  female
4         3    male
..      ...     ...
886       2    male
887       1  female
888       3  female
889       1    male
890       3    male

[891 rows x 2 columns]

In [ ]:
df.iloc[ : , 2:5 ] # will give column from 2nd to 4th index , final index is exclusive

     Pclass                                               Name     Sex
0         3                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         3                             Heikkinen, Miss. Laina  female
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4         3                           Allen, Mr. William Henry    male
..      ...                                                ...     ...
886       2                              Montvila, Rev. Juozas    male
887       1                       Graham, Miss. Margaret Edith  female
888       3           Johnston, Miss. Catherine Helen "Carrie"  female
889       1                              Behr, Mr. Karl Howell    male
890       3                                Dooley, Mr. Patrick    male

[891 rows x 3 columns]

In [ ]:
subset=df[df["Sex"]=="male"].copy().reset_index(drop=True)
subset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
2,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
3,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
4,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
572,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
573,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
574,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
575,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
576,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### set_index

In [ ]:
df_with_NameIndex = df.set_index("Name")
df_with_NameIndex

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

### Reseting Index -> For Rows

In [ ]:
jan_sales = pd.DataFrame(
    {"sales" : [200,300,400]},
    index = ["Store_A" , "Store_B" , "Store_C"],
)
jan_sales

         sales
Store_A    200
Store_B    300
Store_C    400

In [ ]:
feb_sales = pd.DataFrame(
    {"sales" : [240 , 303]},
    index = ["Store_A" , "Store_C"]
)
feb_sales

         sales
Store_A    240
Store_C    303

In [ ]:
common_index = jan_sales.index
common_index

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

In [ ]:
feb_sales_aligned = feb_sales.reindex(common_index)

In [ ]:
feb_sales_aligned

         sales
Store_A  240.0
Store_B    NaN
Store_C  303.0

In [ ]:
feb_sales_aligned = feb_sales.reindex(common_index , fill_value=0)

In [ ]:
feb_sales_aligned

         sales
Store_A    240
Store_B      0
Store_C    303

In [ ]:
jan_sales["sales"] - feb_sales_aligned["sales"]

Store_A    -40
Store_B    300
Store_C     97
Name: sales, dtype: int64

### Reindexing For Columns

In [84]:
source_a = pd.DataFrame({
    "Products" : ["Laptop", "Tablet" , "Phone"],
    "Price" : [50000 , 40000 , 30000],
    "Stock" : [20 , 14 , 30]
})
source_a

  Products  Price  Stock
0   Laptop  50000     20
1   Tablet  40000     14
2    Phone  30000     30

In [81]:
source_b = pd.DataFrame({
    "Products" : ["Laptop" , "Tablet" , "Phone"],
    "Battery" : [5 , 8 , 25]
})
source_b

  Products  Battery
0   Laptop        5
1   Tablet        8
2    Phone       25

In [82]:
source_a_column = source_a.columns
source_a_column

Index(['Products', 'Price', 'Stock'], dtype='str')

In [83]:

source_b_aligned = source_b.reindex(columns = source_a_column , fill_value = 0)
source_b_aligned

  Products  Price  Stock
0   Laptop      0      0
1   Tablet      0      0
2    Phone      0      0

In [90]:
all_columns = source_a.columns.union(source_b.columns)

source_b_a_columns = source_b.reindex(columns = all_columns , fill_value = 0)
source_b_a_columns

   Battery  Price Products  Stock
0        5      0   Laptop      0
1        8      0   Tablet      0
2       25      0    Phone      0