In [11]:
import pandas as pd

### Custom Based Column Creation based on login

In [12]:
data = pd.DataFrame({
    'name' : ["Sumit","Shivam","Saket"],
    'age' : [21,13,16],
    'city' : ["Bangaluru" , "Pune" , "Hydrabad"]
})
data

     name  age       city
0   Sumit   21  Bangaluru
1  Shivam   13       Pune
2   Saket   16   Hydrabad

In [15]:
"""
experience = []
for index , row in data.iterrows():
    if row["age"]>18:
        experience.append("young")
    else:
        experience.append("senior")
"""

values=['young' if row["age"]<18 else "senior" for index,row in data.iterrows()]
data['experience'] = values

In [16]:
data

     name  age       city experience
0   Sumit   21  Bangaluru     senior
1  Shivam   13       Pune      young
2   Saket   16   Hydrabad      young

In [ ]:
# Vectorized way
data['experience'] = data['age'].apply(lambda age : 'young' if age<18 else 'senior')

In [18]:
data

     name  age       city experience
0   Sumit   21  Bangaluru     senior
1  Shivam   13       Pune      young
2   Saket   16   Hydrabad      young

In [23]:
data = pd.DataFrame({
    'name' : ["Sumit","Shivam","Saket"],
    'age' : [21,13,16],
    'city' : ["Bangaluru" , "Pune" , "Hydrabad"]
})
data

     name  age       city
0   Sumit   21  Bangaluru
1  Shivam   13       Pune
2   Saket   16   Hydrabad

In [24]:
# kuch to khud se kiya

def filter(age):
    if age<18:
        return "young"
    else:
        return "senior"
data['experience'] = data['age'].apply(filter)
data

     name  age       city experience
0   Sumit   21  Bangaluru     senior
1  Shivam   13       Pune      young
2   Saket   16   Hydrabad      young