In [2]:
import pandas as pd
import numpy as np

np.random.seed(0)
df = pd.DataFrame({
    "age": np.random.randint(18, 70, size=10).astype(float),
    "salary": np.random.normal(50000, 15000, size=10),
    "city": ["A","B","A","C","B","A","C","B","A","C"],
    "join_date": pd.date_range("2020-01-01", periods=10)
})
# inject some NaNs
df.loc[[1, 2, 5], "age"] = np.nan
df.loc[[2, 7], "salary"] = np.nan
df.loc[[3, 5], "city"] = np.nan

df_backup = df.copy()
df

    age        salary city  join_date
0  62.0  64251.326263    A 2020-01-01
1   NaN  47729.641876    B 2020-01-02
2   NaN           NaN    A 2020-01-03
3  21.0  56158.977529  NaN 2020-01-04
4  21.0  52160.653567    B 2020-01-05
5   NaN  71814.102604  NaN 2020-01-06
6  27.0  61415.565877    C 2020-01-07
7  37.0           NaN    B 2020-01-08
8  39.0  56657.948491    A 2020-01-09
9  68.0  55005.114911    C 2020-01-10

In [3]:
df.isnull().sum()

age          3
salary       2
city         2
join_date    0
dtype: int64

In [5]:
df.isnull().mean() * 100

age          30.0
salary       20.0
city         20.0
join_date     0.0
dtype: float64

In [4]:
df.count()

age           7
salary        8
city          8
join_date    10
dtype: int64

In [6]:
df

    age        salary city  join_date
0  62.0  64251.326263    A 2020-01-01
1   NaN  47729.641876    B 2020-01-02
2   NaN           NaN    A 2020-01-03
3  21.0  56158.977529  NaN 2020-01-04
4  21.0  52160.653567    B 2020-01-05
5   NaN  71814.102604  NaN 2020-01-06
6  27.0  61415.565877    C 2020-01-07
7  37.0           NaN    B 2020-01-08
8  39.0  56657.948491    A 2020-01-09
9  68.0  55005.114911    C 2020-01-10

### Simple Imputation

In [7]:
df["age"] = df["age"].fillna(df["age"].median())

In [15]:
df["city"] = df["city"].fillna(df["city"].mode()[0])

### Handle Time-Series Data

In [21]:
# forward fill -> imputing the value with the previous value
# backward fill -> in backward fill , missing value is imputed using by next value

df_ts = df.sort_values("join_date")
df_ts = df["join_date"].ffill()
df_ts

0   2020-01-01
1   2020-01-02
2   2020-01-03
3   2020-01-04
4   2020-01-05
5   2020-01-06
6   2020-01-07
7   2020-01-08
8   2020-01-09
9   2020-01-10
Name: join_date, dtype: datetime64[us]

In [25]:
# Create synthetic housing data
df = pd.DataFrame({
    'MedInc': [8.3, 8.0, np.nan, 5.5, 3.8, np.nan, 7.0], # Median Income
    'HouseAge': [41, 21, 52, np.nan, 52, 15, 30], # Age of the House
    'MedHouseVal': [4.5, 3.5, 3.5, 3.4, np.nan, 2.8, 3.0] #Median House Value
})
print("Original synthetic housing data with missing values:")
df

Original synthetic housing data with missing values:

   MedInc  HouseAge  MedHouseVal
0     8.3      41.0          4.5
1     8.0      21.0          3.5
2     NaN      52.0          3.5
3     5.5       NaN          3.4
4     3.8      52.0          NaN
5     NaN      15.0          2.8
6     7.0      30.0          3.0